/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.extant.vl2;
import com.extant.utilities.Julian;
import com.extant.utilities.LogFile;
import java.awt.Color;

/**
 * TODO     THIS CLASS MAY BE OBSOLETE AND NOT USED IN VL2
 *
 * @author jms
 */
@SuppressWarnings("serial")
public class EnterTrans
    extends javax.swing.JFrame
{
    // Inherited Variables
    static String entityName;
    static String entityDir;
    static String year;
    static String entityRemoteDir;
    //static String entityPropsFilename;
    //static XProperties props;
    static String chartFilename;
    static Chart chart;
    static ChartTree chartTree;
    static String glFilename;
    
    // Local Variables
    LogFile logger = new LogFile();
    Color defaultBackground;
    String transType;
    String jRef;
    Julian trDate;
    
    public EnterTrans()
    {
if (txtDate == null) System.out.println("txtDate is null! (EnterTrans:40)");
        defaultBackground = txtDate.getBackground();
        txtCashAcct.requestFocusInWindow();
        jRef += transType + trDate.toString( "mm" );
    }
    
    public void setTransType(String type)
    {
        if      (type.equals("CR")) lblTransType.setText("Cash Receipts");
        else if (type.equals("CD")) lblTransType.setText("Cash Disbursements");
        else if (type.equals("JE")) lblTransType.setText("Journal Entries");
        else logger.logFatal("Invalid transType=" + type);
        transType = type;
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblEntName = new javax.swing.JLabel();
        lblTransType = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtCashAcct = new javax.swing.JTextField();
        lblCashAcctDescr = new javax.swing.JLabel();
        lblCashBal = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jComboBoxAcctNo = new javax.swing.JComboBox<>();
        txtDescriiption = new javax.swing.JTextField();
        lblTransTotals = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        btnViewEntries = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnPost = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEntName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEntName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntName.setText("Entity Name");

        lblTransType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTransType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Transaction Date"));
        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateFocusLost(evt);
            }
        });

        txtCashAcct.setBorder(javax.swing.BorderFactory.createTitledBorder("Cash Account"));

        lblCashAcctDescr.setText("Cash Account Description");

        lblCashBal.setText("Cash Balance");

        txtAmount.setBorder(javax.swing.BorderFactory.createTitledBorder("Amount"));

        jComboBoxAcctNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAcctNo.setBorder(javax.swing.BorderFactory.createTitledBorder("Account Number"));

        txtDescriiption.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        lblTransTotals.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Transaction Totals", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnAddItem.setText("Add Item");

        btnViewEntries.setText("View Entries");

        btnClose.setText("Close");

        btnPost.setText("Post Transaction");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEntName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTransType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescriiption)
                    .addComponent(lblTransTotals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(txtDate))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxAcctNo, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(txtCashAcct, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCashAcctDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCashBal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(btnAddItem)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnViewEntries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addComponent(btnClose)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblEntName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTransType)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCashAcctDescr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCashBal))
                    .addComponent(txtCashAcct)
                    .addComponent(txtDate))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jComboBoxAcctNo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescriiption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTransTotals, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddItem)
                            .addComponent(btnClose))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnViewEntries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPost)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusLost
        if ( new Julian(txtDate.getText()).isValid())
            txtDate.setBackground( defaultBackground );
        else
        {
            txtDate.setBackground( Color.yellow );
            txtDate.requestFocus();
        }
    }//GEN-LAST:event_txtDateFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterTrans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPost;
    private javax.swing.JButton btnViewEntries;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxAcctNo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCashAcctDescr;
    private javax.swing.JLabel lblCashBal;
    private javax.swing.JLabel lblEntName;
    private javax.swing.JLabel lblTransTotals;
    private javax.swing.JLabel lblTransType;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCashAcct;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescriiption;
    // End of variables declaration//GEN-END:variables
}
